"""adding course, lesson and tags

Revision ID: 810bdb8858ca
Revises: a1b2c3d4e5f6
Create Date: 2026-05-02 00:13:27.915167

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "810bdb8858ca"
down_revision: Union[str, Sequence[str], None] = "a1b2c3d4e5f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("category", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column("tag_id", sa.Integer(), nullable=True),
        sa.Column("enrol_num", sa.Integer(), nullable=False),
        sa.Column("cover_img", sa.String(), nullable=False),
        sa.Column(
            "level",
            sa.Enum("beginner", "intermediate", "expert", name="course_level"),
            nullable=False,
        ),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("lesson_count", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tag_id"],
            ["tags.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "lessons",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("learning", sa.Text(), nullable=False),
        sa.Column("nosql_id", sa.UUID(), nullable=False),
        sa.Column(
            "type", sa.Enum("build", "learn", name="lesson_type"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("lessons")
    op.drop_table("courses")
    op.drop_table("tags")
    # ### end Alembic commands ###
