"""add order to lessons

Revision ID: 9ba532e50095
Revises: ed27b1182b5a
Create Date: 2026-05-07 08:35:21.790731

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "9ba532e50095"
down_revision: Union[str, Sequence[str], None] = "ed27b1182b5a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("lessons", sa.Column("order", sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lessons", "order")
    # ### end Alembic commands ###
